name: Publish on Docker Hub and Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN}}/${{ secrets.DOCKER_NAME }}:latest
          secrets: |
            "TOKEN=${{ secrets.TOKEN }}"
      -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker stop ${{ secrets.DOCKER_NAME }}
            docker rm ${{ secrets.DOCKER_NAME }}
            docker system prune -f
            docker run -d --name ${{ secrets.DOCKER_NAME }} ${{ secrets.DOCKER_LOGIN}}/${{ secrets.DOCKER_NAME }}:latest
